version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      - SQLITE_PATH=/sqlite.db
    env_file:
      - .env
    volumes:
      - "./static:/app/app/static/"
      - "./data/sqlite.db:/sqlite.db"